# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MapsTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MapsTest
  pod 'YandexMapsMobile', '4.7.0-lite'

  target 'MapsTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MapsTestUITests' do
    # Pods for testing
  end

end
